title: "Abigail Hartzell"
description: "My personal portfolio site."
remote_theme: cotes2020/jekyll-theme-chirpy

theme_color: "#6d33a2" # Purple accent
font: "Inter, Rubik, Nunito" # Other options are Roboto, Arial, sans-serif, Montserrat, Quicksand, Poppins, Raleway
