title: "Abigail Hartzell"
description: "My personal portfolio site."
theme: jekyll-theme-tactile

# Contact Info Section
email: your.email@example.com
linkedin: abigail-hartzell
github_username: abigailhartzell

# Build settings
markdown: kramdown
